### ISSUE TITLE
민재님 firebase에 유저 데이터 추가하고 수정도 좀 해야 되는뎅 ㅠ..... 권한좀 주실 수 있나여 

### ISSUE THREAD

**Issue by J-SoYoung** [GeekChicShop/GeekChic#102]
firebase안들어가고 api로 유저정보 이것저것 테스느 할라니.... 복잡시러워서

https://support.google.com/firebase/answer/7000272?hl=ko#zippy=%2C%EC%9D%B4-%EB%8F%84%EC%9B%80%EB%A7%90%EC%97%90%EB%8A%94-%EB%8B%A4%EC%9D%8C%EC%9D%98-%EB%82%B4%EC%9A%A9%EC%9D%B4-%EB%8B%B4%EA%B2%A8-%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4

설정에 권한 추가하면 나도 민재님 firebase db에 접속할 수 있는거 같은데
한번 확인쫌 ㅎㅐ주삼요ㅠ

**Comment by MJ-Dev92** [comment]
추가 받을 이메일 주소 하나만 남겨주세요 ㅠㅠ

**Comment by J-SoYoung** [comment]
앗!! 넵 thdud@gmail.com 요고용~
