### ISSUE TITLE
질문!!@_@ 마이페이지 제목

### ISSUE THREAD

**Issue by J-SoYoung** [GeekChicShop/GeekChic#14]
마이 아이콘 클릭했는데, 
마이페이지 메인 타이틀이 [ 내프로필 ] 이거덩요
프로필 내용만 있는건 아니니까
-> 마이페이지 or 마이 이렇게 바꾸는거 어때여 

![image](https://github.com/GeekChicShop/GeekChic/assets/85012454/c18b4218-cabd-4efa-bfde-dff43917441a)

**Comment by MJ-Dev92** [comment]
네 좋아용~!
