### ISSUE TITLE
Merge : 주문 내역 merge main까지 했습니다. pull 받고 확인해주세요

### ISSUE THREAD

**Issue by MJ-Dev92** [GeekChicShop/GeekChic#142]
- 기존 api 생각대로 바꿔서 post했습니다 보고 이상한 점 있으시면 말씀해 주세요.
- 기존에 있던 buyerInfo는 굳이 객체를 생성하지 않아도 된다라고 생각되서 객체를 생성하지 않았고, items만 객체로 필요한 데이터 추가했습니다. 확인해주세요.
- carts부분에서 전체 구매만 구현해보고 items 배열로 map을 사용해서 ui에 구현해본 뒤 수정할 가능성있음.

**Comment by J-SoYoung** [comment]
ㅇㅋㅇㅋㅇ 잘하셧슴요 
해당 데이터에 맞게 컴포넌트 변경했습니다
