### ISSUE TITLE
민재님. 왕큰일남. DB.... 사라짐........................... 분명히 url userData/message 경로로 추가했는데..... 

### ISSUE THREAD

**Issue by J-SoYoung** [GeekChicShop/GeekChic#149]
!!!!!!!!!!!!!!!!!!!! 헐랭요 민재님 큰일남 DB사라짐. 
허.어~~~~~~~~~ ㅋㅋㅋㅋㅋㅋ

메세지 firebase에 추가하려고 url 작성하고 했는디. 

아..... ref경로 잘못 입력해서 엎어쓰기 됐나보다. 
우짜누..............................................................................................................................
허우...쏘리 지송 헝.ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ

![泣くなみだGIF](https://github.com/user-attachments/assets/168581b7-1ec0-4afe-a2c6-912b11ab26a6)

**Comment by J-SoYoung** [comment]
일단누............. 로그인하면....................... 
ㅠㅡㅠ.. 유저데이터는 다시 생성되는데................
상품은 없뚜.........................헝 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

그저웃지요,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, 헝..................쏴리이 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by J-SoYoung** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ늦어섴ㅋㅋ카톡안함ㅋㅋㅋㅋㅋㅋㅋ 낼 보고 헤헿... 톡해여 헝ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by MJ-Dev92** [comment]
ㅋㅋㅋㅋㅋㅋ 오키 확인했습니다 !! 데이터 다시 넣고 체크해볼게요 ㅋㅋㅋㅋㅋ
