### ISSUE TITLE
Merge : feat/message -> dev : 쪽지보내기 db저장 및 UI구현중. dev pull받고 작업헤주시요 

### ISSUE THREAD

**Issue by J-SoYoung** [GeekChicShop/GeekChic#155]
- 당황해서 코드 이제사 제대로 봤네유. 
- firebase 코드 이전꺼 복사해서 쓰다가 하나 덜바꿔서ㅠㅠ 데이터 다 엎어쓴거였어요
- database에 저장하는게 아니고 messageRef에 저장했어야 했는디ㅠㅠ.................
![image](https://github.com/user-attachments/assets/e637b874-e3ac-4835-af6c-814bcac8bbe9)

- 여튼..... message 제대로 추가했씀다..헝...헝..ㅋ

**Comment by J-SoYoung** [comment]
일단 자야지. 굳밤. ㅋㅋㅋㅋㅋㅋㅋ

**Comment by MJ-Dev92** [comment]
고생하셨습니다 !! ㅋㅋㅋㅋ 확인해 볼게요!!
