### ISSUE TITLE
Merge : dev -> main에 댓글 이미지 추가 기능 pull 받아주세요

### ISSUE THREAD

**Issue by MJ-Dev92** [GeekChicShop/GeekChic#216]
- 댓글 추가 시 댓글 리스트에서 이미지는 구현 
- 댓글 작성 중 hover할 때 이미지를 어떻게 구현해야 하는지 생각해봐야함

**Comment by J-SoYoung** [comment]
오 잘 작동하네요!! 
근데 댓글 작성에서 UI가 바로 업데이트 안되는데 알고 게신가유!!!! 
아직 리팩토링 하기 전이라 그런가 ㅎㅎ 
여튼~ 별은 예쁘게 ㅋㅋ나오네윸ㅋ

**Comment by MJ-Dev92** [comment]
네네 댓글도 useMutation으로 사용하여 구현해볼려고 합니다!!
