### ISSUE TITLE
Merge : main <- dev <- feat/admin 했습니다.  작업시 pull받고 install 하고 시작해주세요

### ISSUE THREAD

**Issue by MJ-Dev92** [GeekChicShop/GeekChic#62]
- 상품 등록 데이터베이스에 등록되도록 기능 구현했습니다.
- home 등록버튼, 상품 등록페이지 레이아웃 구현하였습니다.
- feat/admin브랜치에서 push할 시 '현재 브랜치의 끝이 리모트 브랜치보다 뒤에 있으므로 업데이트가 안된다'는 이슈가 생겼습니다.
- 혹시 머지를 feat/admin에 하셨나요??
- 일단 이슈를 해결했습니다. 확인해주세요

**Comment by J-SoYoung** [comment]
머지는 dev랑 main만 했었습미다
