### ISSUE TITLE
로컬스토리지 저장해주신거 지워주셔도 될거같아용 호호호호 ㅎㅎ 

### ISSUE THREAD

**Issue by J-SoYoung** [GeekChicShop/GeekChic#79]
recoil로 유저데이터 가져와 썼어용

**Comment by MJ-Dev92** [comment]
애초에 로컬스토리지 이용을 recoil사용해서 상태관리를 했는데 다른 방법으로 하셨다는 건가용?

**Comment by J-SoYoung** [comment]
const firebaseUser = useRecoilValue(userState);
 이렇게 해서 userdata 가져와서 써가지고 localStorage 아예 사용 안하고 있어요!!!
